import = [
    "~/.config/alacritty/theme.toml"
]

[cursor]
style = "Block"

[env]
TERM = "tmux-256color"

[font]
size = 12.0
bold = { family = "Hack Nerd Font", style = "Bold" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
italic = { family = "Hack Nerd Font", style = "Italic" }
normal = { family = "Hack Nerd Font", style = "Regular" }

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "Full"
opacity = 0.90
startup_mode = "Maximized"
blur = true
padding = { x = 5, y = 5}
