
[cursor]
style = "Block"

[env]
TERM = "tmux-256color"

[font]
size = 12.0
bold = { family = "Hack Nerd Font", style = "Bold" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
italic = { family = "Hack Nerd Font", style = "Italic" }
normal = { family = "Hack Nerd Font", style = "Regular" }

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "Buttonless"
opacity = 0.9
startup_mode = "Maximized"
padding = { x = 3, y = 3 }
dynamic_padding = true

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/theme.toml"
]
