tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "awscli"
brew "awslogs"
brew "bash-completion"
brew "certbot"
brew "imagemagick"
brew "libdmtx"
brew "dmtx-utils"
brew "flake8"
brew "git"
brew "gnu-barcode"
brew "gnupg"
brew "htop"
brew "hugo"
brew "iperf"
brew "jmeter"
brew "jq"
brew "lsusb"
brew "mas"
brew "mosh"
brew "mysql", restart_service: true
brew "nmap"
brew "node"
brew "pinentry-mac"
brew "pipenv", link: false
brew "reattach-to-user-namespace"
brew "redis"
brew "telnet"
brew "tmux"
brew "unrar"
brew "wget"
brew "zsh"
cask "adobe-creative-cloud"
cask "alacritty"
cask "battle-net"
cask "beoplay-software-update"
cask "docker"
cask "firefox"
cask "flashforge-flashprint"
cask "fliqlo"
cask "font-source-code-pro"
cask "ftdi-vcp-driver"
cask "google-chat"
cask "google-chrome"
cask "google-drive-file-stream"
cask "java"
cask "lastpass"
cask "macvim"
cask "microsoft-office"
cask "postman"
cask "rocket-chat"
cask "sourcetree"
cask "spotify"
cask "steam"
cask "transmission"
cask "transmit"
cask "vlc"
cask "whatsapp"
cask "wkhtmltopdf"
mas "Bandwidth+", id: 490461369
mas "JSONPeep", id: 1458969831
mas "Reeder", id: 880001334
mas "StuffIt Expander", id: 919269455
mas "Twitter", id: 1482454543
mas "WireGuard", id: 1451685025
