tap "cloudflare/cloudflare"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "awscli"
brew "awslogs"
brew "bash-completion"
brew "certbot"
brew "imagemagick"
brew "libdmtx"
brew "dmtx-utils"
brew "ffmpeg"
brew "git"
brew "gnu-barcode"
brew "gnupg"
brew "hugo"
brew "jq"
brew "lsusb"
brew "mas"
brew "mysql"
brew "neovim"
brew "nmap"
brew "node"
brew "pinentry-mac"
brew "pipenv", link: false
brew "telnet"
brew "unrar"
brew "wget"
brew "cloudflare/cloudflare/cloudflared"
cask "firefox"
cask "font-source-code-pro"
cask "ftdi-vcp-driver"
cask "google-chat"
cask "google-chrome"
cask "iterm2"
cask "lastpass"
cask "macvim"
cask "microsoft-office"
cask "postman"
cask "spotify"
cask "transmit"
cask "vlc"
cask "whatsapp"
cask "wkhtmltopdf"
cask "x-lite"
mas "AdBlock", id: 1402042596
mas "Bandwidth+", id: 490461369
mas "JSONPeep", id: 1458969831
mas "Reeder", id: 880001334
mas "StuffIt Expander", id: 919269455
mas "Twitter", id: 1482454543
