after-login-command = []
after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

[mode.main.binding]
alt-period = 'layout tiles accordion'
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
alt-shift-h = 'workspace h'
alt-shift-j = 'workspace j'
alt-shift-k = 'workspace k'
alt-shift-l = 'workspace l'
alt-cmd-h = 'move-workspace-to-monitor prev'
alt-cmd-l = 'move-workspace-to-monitor next'
alt-up = 'resize width +50'
alt-down = 'resize width -50'
alt-f = 'fullscreen'
alt-g = 'mode group'
alt-m = 'mode move'
alt-s = 'mode service'

[mode.group.binding]
alt-h = ['join-with left', 'mode main']
alt-j = ['join-with down', 'mode main']
alt-k = ['join-with up', 'mode main']
alt-l = ['join-with right', 'mode main']
esc = 'mode main'
enter = 'mode main'

[mode.move.binding]
alt-h = 'move left'
alt-j = 'move down'
alt-k = 'move up'
alt-l = 'move right'
alt-shift-h = ['move-node-to-workspace h', 'mode main']
alt-shift-j = ['move-node-to-workspace j', 'mode main']
alt-shift-k = ['move-node-to-workspace k', 'mode main']
alt-shift-l = ['move-node-to-workspace l', 'mode main']
esc = 'mode main'
enter = 'mode main'

[mode.service.binding]
r = ['reload-config', 'mode main']
shift-r = ['flatten-workspace-tree', 'mode main']
# f = ['layout floating tiling', 'mode main']
esc = 'mode main'
